### ISSUE TITLE
10:1 attenuator on analogue channel

### ISSUE THREAD

**Issue by tony1tf** [pico-coder/sigrok-pico#14]
Hi

A question -I want to use a 10:1 attenuator on the analogue channels. I would like the voltage displayed correctly in PulseView.  Am I right in believing that all that is needed is a change in pico_sdk_sigrok to line 163 in srdevice.h from 25700 to 257812 (= 33V/128 uV)

Tony

**Comment by pico-coder** [comment]
Yes, that's it.
However, Pulseview has an "add math signal" (look for the f(x) in the menu bar, that allows you to manipulate channel values.  That might be a bit faster if you need to swap attenuators :).

**Comment by tony1tf** [comment]
Hi Shawn
Thanks for the suggestion.
I tried the f(x) signal - it's OK, but you can't disable the original channel, else it can't pick it up to be multiplied by 10, so it wastes screen space, which is pretty special when you could have 22 digital and 3 analogues.
Tony

**Comment by pico-coder** [comment]
Closing this out because the question is answered, happy tracing.
