### ISSUE TITLE
Need better build instructions

### ISSUE THREAD

**Issue by dov** [pico-coder/sigrok-pico#43]
I cloned this repo and tried to follow the build instructions in SigrokBuildNotes.md, but I failed to create a working configuration.

Here is my interpretation of what should be done and my questions

1. git clone the mainline repo - **ok**
2. `git clone sigrok-utils - **ok** - 
3. - Oops. There is no 3 :-)
4. `cd <path>sigrog-util/source` - **ok**
5. `./new-driver "RaspberryPI PICO"` - **ok**, but after running this command it is not clear what to do with its outputs. They are written to `sigrok-util/source` but what should be done with these files? The next step seems disconnected
6-10. cd libsigrok && ./autogen.sh && ./configure && make

I did all of this, but libsigrok `.configure` did not list the pico in the list of hardware drivers.

I tried manually to manually add the pico driver to `configure.ac` which made libsigrok `configure` pick up the hardware driver.

But after compiling, installing libsigrok and sigrok-cli I tried connecting, and got the message:

```
$ sigrok-cli -l 2 -d raspberrypi-pico:conn=/dev/ttyACM0:serialcomm=115200/flow=0 --scan
Driver raspberrypi-pico not found.
```

**Comment by pico-coder** [comment]
With the release of this to mainline, it is no longer needed to mess with sigrok-utils to create the new driver, and there should be nothing special about building.
Further, most people will have no good reason to try to build with mainline install releases support this.
So closing out.
